# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 358)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 241, 61))
        self.label.setObjectName("label")
        self.pushButton_Clear = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Clear.setGeometry(QtCore.QRect(0, 60, 61, 61))
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.pushButton_div = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_div.setGeometry(QtCore.QRect(180, 60, 61, 61))
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_mod = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_mod.setGeometry(QtCore.QRect(120, 60, 61, 61))
        self.pushButton_mod.setObjectName("pushButton_mod")
        self.pushButton_negative = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_negative.setGeometry(QtCore.QRect(60, 60, 61, 61))
        self.pushButton_negative.setObjectName("pushButton_negative")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 120, 61, 61))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 120, 61, 61))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_mult = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_mult.setGeometry(QtCore.QRect(180, 120, 61, 61))
        self.pushButton_mult.setObjectName("pushButton_mult")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 120, 61, 61))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 180, 61, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 180, 61, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_minus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_minus.setGeometry(QtCore.QRect(180, 180, 61, 61))
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 180, 61, 61))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 240, 61, 61))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 240, 61, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_plus = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(180, 240, 61, 61))
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 240, 61, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_Zero = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Zero.setGeometry(QtCore.QRect(0, 300, 121, 61))
        self.pushButton_Zero.setObjectName("pushButton_Zero")
        self.pushButton_equal = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_equal.setGeometry(QtCore.QRect(180, 300, 61, 61))
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_dec = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_dec.setGeometry(QtCore.QRect(120, 300, 61, 61))
        self.pushButton_dec.setObjectName("pushButton_dec")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton_Clear.setText(_translate("MainWindow", "C"))
        self.pushButton_div.setText(_translate("MainWindow", "/"))
        self.pushButton_mod.setText(_translate("MainWindow", "%"))
        self.pushButton_negative.setText(_translate("MainWindow", "+/-"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_mult.setText(_translate("MainWindow", "X"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_Zero.setText(_translate("MainWindow", "0"))
        self.pushButton_equal.setText(_translate("MainWindow", "="))
        self.pushButton_dec.setText(_translate("MainWindow", "."))

